language: node_js

node_js: '11'

sudo: false

git:
  depth: 3

cache:
  directories:
    - ~/.npm  # cache npm's cache
    - ~/npm   # cache latest npm
    - node_modules

before_install: |
  [[ ! -x ~/npm/node_modules/.bin/npm ]] && {
    cd ~/npm && npm install npm
    cd -
  } || true
  export PATH=~/npm/node_modules/.bin:$PATH

install: npm install --ignore-scripts

jobs:
  include:
    - node_js: '11'
      after_success: npm start coveralls
    - node_js: '10'
    - node_js: '8'
    - node_js: 'node'
      name: 'Node.js: nightly'
      env:
        - NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly
        - NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/nightly
    - node_js: 'node'
      name: 'Node.js: canary'
      env:
        - NODEJS_ORG_MIRROR=https://nodejs.org/download/v8-canary
        - NVM_NODEJS_ORG_MIRROR=https://nodejs.org/download/v8-canary

  allow_failures:
    - name: 'Node.js: nightly'
    - name: 'Node.js: canary'
