sudo: false

language: node_js

node_js:
  - 8.3
  - 9
  - 10

branches:
  only:
    - master

git:
  depth: 3

cache:
  directories:
    - node_modules
    - ~/.npm

script:
  - npm run test

after_success:
  - npm run coverage
